version: "3.3"

services:
  commento:
    image: registry.gitlab.com/commento/commento:latest
    ports:
      - 8787:8787
    env_file:
      - VOLUME_DIR/commento.env
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comments.entrypoints=http"
      - "traefik.http.routers.comments.rule=Host(`comments.example.com`)"
      - "traefik.http.middlewares.comments-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.comments.middlewares=comments-https-redirect"
      - "traefik.http.routers.comments-secure.entrypoints=https"
      - "traefik.http.routers.comments-secure.rule=Host(`comments.example.com`)"
      - "traefik.http.routers.comments-secure.tls=true"
      - "traefik.http.routers.comments-secure.service=comments"
      - "traefik.http.services.comments.loadbalancer.server.port=8000"
      - "traefik.docker.network=web"

networks:
  web:
    external:
      name: web
  internal:
    external:
      name: internal
