api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    forwardedHeaders:
      insecure: true
  https:
    address: ":443"
    forwardedHeaders:
      insecure: true

providers:
  providersThrottleDuration: 2s
  docker:
    network: web
    watch: true
    exposedByDefault: false

log: {}

certificatesResolvers:
  le:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: YOUR_EMAIL
      storage: acme.json
      dnsChallenge:
        provider: digitalocean
        delayBeforeCheck: 0
