version: "3.3"
services:
  plausible:
    depends_on:
      - geoip
    environment:
      - GEOLITE2_COUNTRY_DB=/geoip/GeoLite2-Country.mmdb
    volumes:
      - geoip:/geoip:ro

  geoip:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # update every 7 days
      - GEOIPUPDATE_ACCOUNT_ID=<your-account-id>
      - GEOIPUPDATE_LICENSE_KEY=<your-license-key>
    volumes:
      - geoip:/usr/share/GeoIP

volumes:
  geoip:
    driver: local
